### ISSUE TITLE
Unpkg link doesn't work

### ISSUE THREAD

**Issue by badgeminer** [misode/deepslate#20]
when using the ```<script src="https://unpkg.com/deepslate@0.15.10"></script>``` found in the readme will not work,
giving this error message instead 
`GET https://unpkg.com/deepslate@0.16.0-beta.2/dist/deepslate.umd.js net::ERR_ABORTED 404`

**Comment by misode** [comment]
In the meantime, this version seems to work: https://unpkg.com/deepslate@0.14.0

**Comment by badgeminer** [comment]
thanks

**Comment by misode** [comment]
This has been fixed in `v0.16.1`
