### ISSUE TITLE
Compatibility with blocks added by mods?

### ISSUE THREAD

**Issue by jumble** [misode/deepslate#28]
If supported at all, what should the workflow generally look like to ensure that most well-behaved blocks from an arbitrary mod can be e.g. rendered via the deepslate web renderer?

**Comment by misode** [comment]
This is what the resources are for that you pass to the `StructureRenderer`. See the demo: https://github.com/misode/deepslate/blob/main/demo/main.ts#L116. Primarily you need the blockstates (`BlockDefinition`), model (`BlockModel`) and texture files from the resource pack. The tricky part will be creating a texture atlas with all the textures, for vanilla it uses pre-made atlases from mcmeta: https://github.com/misode/mcmeta/blob/atlas/all/atlas.png. But if you have a small amount of separate textures you can use the `TextureAtlas.fromBlobs` static method.

Let me know if you need more help with getting it to work.
