### ISSUE TITLE
waterlogged blocks are rendered without water

### ISSUE THREAD

**Issue by casu-dev** [misode/deepslate#34]
When running the demo and adding this block to the structure you get the following result. 
```ts
structure.addBlock([2, 1, 0], 'minecraft:acacia_fence', { waterlogged: 'true' })
```
![image](https://github.com/user-attachments/assets/084d6979-aa7e-4ae1-9c61-bf359be25b01)
The fence is expected to be inside a water source block.

**Comment by misode** [comment]
Fixed in #35
