### ISSUE TITLE
Density function precision issues

### ISSUE THREAD

**Issue by jacobsjo** [misode/deepslate#42]
Deepslate density functions aren't always accurate when floating point precision has an effect. I'll look into this more in the future. 

Discord discussion: https://discord.com/channels/738046951236567162/750811307925831841/1318399656148860970

- splines use float, we we should use `Math.fround()` to handle precision accurately
- some casts to int are apparently wrong

**Comment by unnecessarymb** [comment]
https://discord.com/channels/738046951236567162/750811307925831841/1291393498658111629
> At <https://github.com/misode/deepslate/blob/36dfb49f23839ab99e9582ef4057627499b4fb76/src/math/noise/PerlinNoise.ts#L82>, you use `Math.floor`. However, in the MC source code, a utility function is used that clamps the result to [-2^63+1, 2^63-1]. At very high firstOctave levels, this causes the ImprovedNoise calls to diverge, due to extreme precision loss in MC’s case. This divergence is of particular use to me, as it allows me to specify a cube/square/horizontal region at any offset using only two noise queries. I’m pinging here instead of writing a full issue because I’m not entirely sure to what degree a fix would be in scope, as that code hasn’t been touched in two years and this hasn’t come up before me, and I would welcome input.
